const server = require("../server.js");
const noblox = require("noblox.js");
const config = require("../config.json");
const events = require("../events.js");
const Config = require("../config.js");
const cookie = require("../cookie.js");
process.env.Hahahahahahahbq;
process.env.user_id;
var login = true;
let LoginType = 'cookie, no captcha, username and, password, user id';
var saveLogin = true;